tina = User.create(first_name: "Tina", last_name: "Fey", email: "Tina@fey.com", password: "asdasd" )
high = tina.portfolios.create(name:"High Risk")
low = tina.portfolios.create(name:"Low Risk")
high.stocks.create(name: "Apple", symbol: "AAPL", volume: 5, buy_price: 100)
high.stocks.create(name: "Alibaba", symbol: "BABA", volume: 10, buy_price: 200)
high.stocks.create(name: "Athenahealth", symbol: "ATHN", volume: 5, buy_price: 50)
low.stocks.create(name: "Amazon", symbol: "AMZN", volume: 5, buy_price: 1000)
low.stocks.create(name: "Aflac", symbol: "AFL", volume: 10, buy_price: 50)
